openapi: '3.0.3'
info:
  title: DaaS-NodeJS
  version: '1.0'
  
  contact:
    name: API Support
    email: alessio.farfaglia@gmail.com
  
  license:
    name: MPL-2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/

servers:
  - url: http://localhost:{port}/api
    description: Development server
    variables:
      port:
        default: '3000'
        description: default port for the development server


externalDocs:
  url: 'https://github.com/sebyone/daas-nodejs'

tags:
  - name: configuration
    description: API per la configurazione del nodo daas
  - name: lifecycle
    description: API per gestire il del ciclo di vita del nodo daas (avvio, stop, riavvio)
  - name: commands
    description: API per l'invio di comandi ai nodi daas, come invio di messaggi
  - name: receivers
    description: API per la gestione dei receivers, nodi locali che ricevono e potenzialmente inviano messaggi
  - name: remotes
    description: API per la mappare nodi remoti ai receivers e gestire i nodi remoti
  - name: DDOs
    description: Daas Data Object, messaggi inviati tra i nodi daas
  - name: devices
  - name: device models
  - name: programming
    description: API per la programmazione remota dei dispositivi concatenando regole di programmazione
  

#region Components

components:
  schemas:
    DinLocal:
      type: object
      properties:
        id:
          type: integer
          description: ID del receiver
        title:
          type: string
          description: Nome del receiver
        acpt_all:
          type: boolean
          description: Flag per accettare messaggi da nodi non mappati
          default: false
        enable:
          type: boolean
          default: false
        din_id:
          type: integer
          description: ID del DIN associato al receiver
        din:
          $ref: '#/components/schemas/Din'
        links:
          type: array
          items:
            $ref: '#/components/schemas/DinLink'


    DinLink:
      type: object
      properties:
        id:
          type: integer
          description: ID del link
        url:
          type: string
          description: dati del link, es. IP in caso di link di tipo 2
          example: "127.0.0.1:2001"
        link:
          type: integer
          description: tipo di link
          enum: [1, 2, 3, 4]
          example: 2
        din_id:
          type: integer
          description: ID del DIN al quale è associato il link
    Din:
      type: object
      properties:
        id:
          type: integer
          description: ID del DIN
        sid:
          type: string
          description: identificatore della rete daas (SID)
        din:
          type: string
          description: identificatore univoco del nodo daas all'interno della rete
        p_res:
          type: string
          description: preferenze di rete dell'utente, (riservatezza, 
          example: "000"
        skey:
          type: string
          description: SKEY del DIN
          example: "9efbaeb2a94f"

    Din_with_links:
      type: object
      properties:
        id:
          type: integer
          description: ID del DIN
        sid:
          type: string
          description: identificatore della rete daas (SID)
        din:
          type: string
          description: identificatore univoco del nodo daas all'interno della rete
        p_res:
          type: string
          description: preferenze di rete dell'utente, (riservatezza, 
          example: "000"
        skey:
          type: string
          description: SKEY del DIN
          example: "9efbaeb2a94f"
        links:
          type: array
          items:
            $ref: '#/components/schemas/DinLink'
      
    DinHasDin:
      type: object
      properties:
        pdin_id:
          type: integer
          description: ID del DIN del nodo padre, in quale mappa il DIN con id 'cdin_id'
        cdin_id:
          type: integer
          description: ID del DIN del nodo figlio, mappato dal nodo padre con id 'pdin_id'
      required:
        - pdin_id
        - cdin_id

    DinHasDin_with_CDin:
      type: object
      properties:
        pdin_id:
          type: integer
          description: ID del DIN del nodo padre, in quale mappa il DIN con id 'cdin_id'
        cdin_id:
          type: integer
          description: ID del DIN del nodo figlio, mappato dal nodo padre con id 'pdin_id'
        cdin:
          $ref: '#/components/schemas/Din'

    Device:
      type: object
      properties:
        id:
          type: integer
          description: ID del device
        device_model_id:
          type: integer
          description: ID del modello del device
        din_id:
          type: integer
          description: ID del DIN associato al device
        name:
          type: string
          description: Nome del device
          maxLength: 45
        latitude:
          type: number
          description: latitudine
          example: 39.3015
        longitude:
          type: number
          description: longitudine
          example: 16.2536
        

    DeviceFull:
      type: object
      properties:
        id:
          type: integer
          description: ID del device
        device_model_id:
          type: integer
          description: ID del modello del device
        din_id:
          type: integer
          description: ID del DIN associato al device
        name:
          type: string
          description: Nome del device
          maxLength: 45
        latitude:
          type: number
          description: latitudine
          example: 39.3015
        longitude:
          type: number
          description: longitudine
          example: 16.2536
        device_model:
          $ref: '#/components/schemas/DeviceModel'
        din:
          $ref: '#/components/schemas/Din'


    DeviceModel:
      type: object
      properties:
        id:
          type: integer
          description: ID del modello del device
          nullable: false
        device_group_id:
          type: integer
          description: ID del gruppo del modello
          nullable: false
        description:
          type: string
          description: descrizione del modello
        serial:
          type: string
          description: seriale del modello
          maxLength: 20
        link_image:
          type: string
          description: collegamento all'immagine del device
          maxLength: 45
        link_datasheet:
          type: string
          description: collegamento alla scheda tecnica
          maxLength: 45
        link_userguide:
          type: string
          description: collegamento al manuale utente
          maxLength: 45

    DeviceModelFull:
      type: object
      properties:
        id:
          type: integer
          description: ID del modello del device
          nullable: false
        device_group_id:
          type: integer
          description: ID del gruppo del modello
          nullable: false
        description:
          type: string
          description: descrizione del modello
        serial:
          type: string
          description: seriale del modello
          maxLength: 20
        link_image:
          type: string
          description: collegamento all'immagine del device
          maxLength: 45
        link_datasheet:
          type: string
          description: collegamento alla scheda tecnica
          maxLength: 45
        link_userguide:
          type: string
          description: collegamento al manuale utente
          maxLength: 45
        device_group:
          $ref: '#/components/schemas/DeviceModelGroup'
        resources:
          type: array
          items:
            $ref: "#/components/schemas/DeviceModelResource"

    DeviceModelGroup:
      type: object
      properties:
        id:
          type: integer
          description: ID del gruppo del modello
          nullable: false
        title:
          type: string
          description: titolo del gruppo
          maxLength: 45
        description:
          type: string
          description: descrizione del gruppo
        link_image:
          type: string
          description: collegamento all'immagine del gruppo
          maxLength: 45
          example: "https://placehold.co/600x400"

    DeviceModelResource:
      type: object
      properties:
        id:
          type: integer
          description: ID della risorsa
          nullable: false
        title:
          type: string
          nullable: false
        device_model_id:
          type: integer
          description: ID del modello di device al quale si riferisce questa risorsa
          nullable: false

    DDO:
      description: Daas Data Object
      type: object
      properties:
        id:
          type: integer
          description: ID del DDO
          nullable: false
          example: 3
        din_id_dst:
          type: integer
          description: ID del DIN che ha ricevuto questo DDO
          nullable: false
          example: 2
        din_id_src:
          type: integer
          description: ID del DIN che ha inviato questo DDO
          nullable: false
          example: 1
        timestamp:
          type: string
          format: date-time
          description: Data e orario di quando è stato inviato il DDO
          nullable: true
          example: 2024-07-21T17:32:28Z
        typeset_id:
          type: integer
          nullable: false
          example: 41
        payload:
          type: string
          format: base
          description: Payload contenuto all'interno del DDO, in codifica Base64
          nullable: true
          example: eyJtZXNzYWdnaW8iOiAiY2lhbyBNb25kbyJ9

    PaginationData: 
      description: Meta dati sulla paginazione dei dati
      properties:
        count:
          type: integer
          description: numero di oggetti contenuti tra i dati della risposta
          minimum: 0
          example: 20
        offset:
          type: integer
          description: gli oggetti contenuti dei dati della risposta partono da questo offset
          minimum: 40
        limit:
          type: integer
          description: numero massimo di oggetti contenuti tra i dati della risposta
          minimum: 0
          example: 20
        total:
          description: numero totale di oggetti per questa query
          type: integer
          minimum: 0
          example: 67



    Error:
      type: object
      properties:
        error_name:
          type: string
          description: Nome dell'errore
          example: "TypeError"
        message:
          type: string
          description: Messaggio di errore

#region Paths
paths:
  /:
    get:
      responses:
        '200':
          description: OK

  /configure:
    post:
      description: Carica la configurazione del nodo locale (per il din_local con id=1)
      tags:
        - configuration
      responses:
        '200':
          description: configurazione applicata.
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /stop:
    post:
      description: Ferma il nodo daas locale
      tags:
        - lifecycle
      responses:
        '200':
          description: Nodo fermato.
        default:
          description: Impossibile fermare il nodo locale.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /start:
    post:
      description: Avvia il nodo daas locale
      tags:
        - lifecycle
      responses:
        '200':
          description: Nodo locale avviato.
        default:
          description: Impossibile avviare il nodo locale.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /restart:
    post:
      description: Riavvia il nodo daas locale
      tags:
        - lifecycle
      responses:
        default:
          description: Non ancora implementato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /send:
    post:
      description: Invia un messaggio tramite il nodo daas locale al DIN specificato
      tags:
        - commands
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                din:
                  type: integer
                  description: Il DIN a cui inviare il messaggio
                typeset:
                  type: integer
                  description: Il typeset del messaggio
                payload:
                  type: object
                  description: Il payload del messaggio
                  nullable: true
              required:
                - din
                - typeset
              example:
                din: 105
                typeset: 701
                payload: { "temperature": 25.5, "humidity": 50 }
      responses:
        '200':
          description: Messaggio inviato.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio inviato.
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /status: 
    get:
      description: Ritorna lo status del nodo locale.
      tags:
        - lifecycle
      responses:
        '200':
          description: Infomazioni sullo stato del nodo.s
          content:
            application/json:
              schema:
                type: object
                properties:
                  lasttime:
                    type: number
                    description: time reference
                  hwver:
                    type: number
                    description: platform (hard-coded) when the node was contructed
                  linked:
                    type: number
                    description: channels counter (0=not linked)
                  sync:
                    type: number
                    description: synchronization status (0=not in sync)
                  lock:
                    type: number
                    description: required security policy
                  sklen:
                    type: number
                    description: security phrase length
                  skey:
                    type: string
                    description: security phrase (UTF-8)
                  form:
                    type: number
                    description: data formatting model
                  codec:
                    type: number
                    description: data encryption level
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /version:
    get:
      description: Restituisce le versioni di librerie e software utilizzate dal nodo.
      tags:
        - configuration
      responses:
        '200':
          description: Versioni delle librerie e del software utilizzate dal nodo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  daasLibrary:
                    type: string
                    description: versione della libreria interna Daas
                    example: "0.17a"
                  nodeGyp:
                    type: string
                    description: versione di node-gyp utilizzata per costruire il binario (daas-sdk)
                    example: "8.0.0"
                  compiler:
                    type: string
                    description: nome del compilatore c++ utilizzato e la sua versione (GCC, Clang/LLVM, MSVC)
                    example: "GCC 10.2.1 20210110"
                  cppStandardLibrary:
                    type: string
                    description: versione della libreria standard c++ utilizzata (GNU libstdc++, LLVM libc++, MSVC STL)
                    example: "GNU libstdc++ 20210110"
                  node:
                    type: string
                    description: versione di Node.js
                    example: "20.17.0"
                  nodeAddonApi:
                    type: string
                    description: versione dell'addon API di Node.js
                    example: "9"

#region Receivers

  /receivers:
    get:
      description: Ritorna una lista di tutti i receivers.
      tags:
        - receivers
      responses:
        '200':
          description: Lista di tutti i receivers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DinLocal'

        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      description: Crea un nuovo receiver
      tags:
        - receivers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                din:
                  $ref: '#/components/schemas/Din'
                title:
                  type: string
                  description: Nome del receiver
              required:
                - din
                - title
              example:
                din: { "sid": "100", "din": "87" }
                title: "Receiver 1"
      responses:
        '200':
          description: Receiver aggiunto con successo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinLocal'
        '400':
          description: Errore nei parametri della richiesta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
  /receivers/count:
    get:
      description: Ritorna il numero di receivers presenti.
      tags:
        - receivers
      responses:
        '200':
          description: Numero di receivers presenti.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Numero di receivers presenti
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /receivers/{receiverId}:
    get:
      description: Ritorna un receiver specifico.
      tags:
        - receivers
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Receiver trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinLocal'
                description: Receiver completo con i dati del DIN associato e i link
        '404':
          description: Receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      description: Aggiorna un receiver specifico.
      tags:
        - receivers
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                din:
                  $ref: '#/components/schemas/Din'
                title:
                  type: string
                  description: Nome del receiver
                enable:
                  type: boolean
                  description: Flag per abilitare/disabilitare il receiver
                acpt_all:
                  type: boolean
                  description: Flag per accettare messaggi da nodi non mappati                
              required:
                # TODO: rendere il din non obbligatorio
                - din
                - title
              example:
                din: { "sid": "100", "din": "87" }
                title: "Receiver 1"
      responses:
        '200':
          description: Receiver aggiornato con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
        '400':
          description: Errore nei parametri della richiesta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Receiver o Din non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
    delete:
      description: Elimina un receiver specifico.
      tags:
        - receivers
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Receiver eliminato con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
        '404':
          description: Receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

#region Receivers links

  /receivers/{receiverId}/links:
    get:
      description: Ritorna i link associati al receiver.
      tags:
        - receivers
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista di tutti i link associati al receiver.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DinLink'
        '404':
          description: Receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      description: Aggiunge un link al receiver.
      tags:
        - receivers
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL del link
                link:
                  type: integer
                  description: Tipo di link
                  enum: [1, 2, 3, 4]
              required:
                - url
                - link
              example:
                link: 2
                url: "151.81.1.4:2001"
      responses:
        '200':
          description: Link aggiunto con successo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinLink'
        '400':
          description: Errore nei parametri della richiesta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /receivers/{receiverId}/links/{id}:
    get:
      description: Ritorna un link specifico associato al receiver.
      tags:
        - receivers
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
        - name: id
          in: path
          description: ID del link
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Link trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinLink'
        '404':
          description: Link non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      description: Aggiorna un link specifico associato al receiver.
      tags:
        - receivers
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
        - name: id
          in: path
          description: ID del link
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL del link
                link:
                  type: integer
                  description: Tipo di link
                  enum: [1, 2, 3, 4]
              example:
                url: "1.2.3.4:6045"
      responses:
        '200':
          description: Link aggiornato con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
        '400':
          description: Errore nei parametri della richiesta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Link non appartiene al receiver.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Link o Receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
    delete:
      description: Elimina un link specifico associato al receiver.
      tags:
        - receivers
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
        - name: id
          in: path
          description: ID del link
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Link eliminato con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
        '404':
          description: Link o Receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Link non appartiene al receiver.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

#region DINs

  /dins:
    get:
      description: Ritorna una lista di tutti i DINs.
      tags:
        - receivers
        - remotes
      responses:
        '200':
          description: Lista di tutti i DINs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Din'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /remotes:
    get:
      description: Ritorna una lista di tutti i nodi remoti, ovvero i DINs non associati ad un receiver.
      tags:
        - remotes
      responses:
        '200':
          description: Lista di tutti i nodi remoti.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Din_with_links'

        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /remotes/count:
    get:
      description: Ritorna il numero di nodi remoti presenti.
      tags:
        - remotes
      responses:
        '200':
          description: Numero di nodi remoti presenti.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Numero di nodi remoti presenti
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

#region Receivers remotes


  /receivers/{receiverId}/remotes:
    get:
      description: Ritorna tutti i nodi mappati sul receiver.
      tags:
        - receiver
        - remotes
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista di tutti i nodi mappati sul receiver.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DinHasDin_with_CDin'
        '404':
          description: Receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


    post:
      description: Associa e modifica un nodo remoto al receiver, se non esiste lo crea.
      tags:
        - receiver
        - remotes
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                din:
                  $ref: '#/components/schemas/Din'
              required:
                - din
            examples:
              new remote:
                value:
                  din: { "sid": "100", "din": "87", "p_res": "011", "skey": "9efb9832494f" }
              existing remote:
                value:
                  din: { "id": 2 }
              existing remote, make changes:
                value:
                  din: { "id": 2, "din": "1669" }

      responses:
        '200':
          description: Nodo remoto associato con successo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinHasDin_with_CDin'
        '400':
          description: Errore nei parametri della richiesta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Receiver o remote non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


    delete:
      description: Elimina tutte le associazione del receiver con i nodi remoti.
      tags:
        - receiver
        - remotes
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Associazioni eliminate con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
        '404':
          description: Receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '501':
          description: Non ancora implementato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /receivers/{receiverId}/remotes/{id}:
    get:
      description: Ritorna un nodo remoto specifico associato al receiver.
      tags:
        - receiver
        - remotes
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
        - name: id
          in: path
          description: ID del nodo remoto
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Nodo remoto trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinHasDin_with_CDin'
        '404':
          description: Receiver o nodo remoto mappato a receiver non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      description: Elimina l'associazione tra il nodo remoto e il receiver, se il nodo remoto non ha altre associazioni, viene cancellato.
      tags:
        - receiver
        - remotes
      parameters:
        - name: receiverId
          in: path
          description: ID del receiver
          required: true
          schema:
            type: integer
        - name: id
          in: path
          description: ID del nodo remoto
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Nodo remoto eliminato con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
        '404':
          description: Receiver o nodo remoto non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

#region Devices


  /devices:
    get:
      description: mostra di tutti i devices.
      tags:
        - devices
      responses:
        '200':
          description: Lista di tutti i devices.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceFull'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      description: Crea un nuovo device, con associato un device model e un DIN.
      tags:
        - devices
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                device_model_id:
                  type: integer
                  description: ID del modello del device
                din_id:
                  type: integer
                  description: ID del DIN associato al device
                name:
                  type: string
                  description: Nome del device
                  maxLength: 45
                latitude:
                  type: number
                  description: latitudine
                  example: 39.3015
                longitude:
                  type: number
                  description: longitudine
                  example: 16.2536
              required:
                - device_model_id
                - din_id
                - name
              example:
                device_model_id: 1
                din_id: 1
                name: "Device 1"
                latitude: 39.3015
                longitude: 16.2536
      responses:
        '200':
          description: Device aggiunto con successo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Errore nei parametri della richiesta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Device model o DIN non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /devices/{deviceId}:
    get:
      description: Ritorna un device specifico.
      tags:
        - devices
      parameters:
        - name: deviceId
          in: path
          description: ID del device
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Device trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceFull'
        '404':
          description: Device non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      description: Aggiorna un device specifico.
      tags:
        - devices
      parameters:
        - name: deviceId
          in: path
          description: ID del device
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                device_model:
                  $ref: '#/components/schemas/DeviceModel'
                serial:
                  type: string
                  description: Seriale del device
                din:
                  $ref: '#/components/schemas/Din'
              required:
                - device_model
                - serial
                - din
              example:
                device_model: { "device_group_id": 1, "productcode": "123400001234", "datasheet": "datasheet", "userguide": "userguide" }
                serial: "1234567890"
                din: { "sid": "100", "din": "87" }
      responses:
        '200':
          description: Device aggiornato con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
        '400':
          description: Errore nei parametri della richiesta.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Device model o DIN non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      description: Elimina un device specifico.
      tags:
        - devices
      parameters:
        - name: deviceId
          in: path
          description: ID del device
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Device eliminato con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
        '404':
          description: Device non trovato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  
  /devices/{deviceId}/ddos/:
    get:
      description: Ritorna i ddo ricevuti dal device specificato
      tags:
        - devices
        - DDOs
      parameters:
        - name: deviceId
          in: path
          description: ID del device che ha ricevuto i DDO
          required: true
          schema:
            type: integer
        - name: offset
          in: query
          description: offset dei DDO ritornati per la paginazione
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Massimo numero di DDO ritornati nella risposta
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
      responses:
        '200':
          description: Pagina di DDO e informazioni sulla paginazione
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/DDO"
                  pagination:
                    $ref: "#/components/schemas/PaginationData"
                    



  

